dist: xenial
language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/qsopt_ex-2.5.10.3"
  - "$HOME/qsopt-ex"
  - "$HOME/python-qsoptex"
addons:
  apt:
    packages:
    - libgmp-dev
    - libgmp10
    - libglpk36
    - libglpk-dev
    - glpk-utils
    - swig
install:
- if echo "$TOXENV" | grep -q "qsoptex"; then
    if [ ! -f "src" ]; then
      mkdir src;
    fi;
    
    pip install Cython; 
    if [ ! -f "$HOME/qsopt-ex/esolver" ]; then
      ( cd src/;
        git clone https://github.com/jonls/qsopt-ex.git;
        cd qsopt-ex/;
        ./bootstrap;
        mkdir build && cd build;
        ../configure --prefix="$HOME/qsopt-ex" && make install;
        cd $HOME );
    fi;
    if [ ! -f "$HOME/python-qsoptex" ]; then
      ( cd src/;
        git clone https://github.com/jonls/python-qsoptex.git;
        cd python-qsoptex/;
        ./setup.py install;    
        cd $HOME );
    fi;
    pip install python-qsoptex;
    export CPATH="$HOME/qsopt-ex/include:$CPATH";
    export LIBRARY_PATH="$HOME/qsopt-ex/lib:$LIBRARY_PATH";
    export LD_LIBRARY_PATH="$HOME/qsopt-ex/lib:$LD_LIBRARY_PATH";
  fi;
- pip install tox coveralls
- pip install tox-travis
- pip install --upgrade six
script: tox -v
after_success: coveralls
matrix:
  include:
  - env: TOXENV=flake
  - env: TOXENV=py36-nosolver,coverage
    python: '3.6'
  - env: TOXENV=py36-glpk,coverage
    python: '3.6'
  - env: TOXENV=py36-qsoptex,coverage
    python: '3.6'
  - env: TOXENV=py37-nosolver,coverage
    python: '3.7'
  - env: TOXENV=py37-glpk,coverage
    python: '3.7'
  - env: TOXENV=py37-qsoptex,coverage
    python: '3.7'
  - env: TOXENV=docs
deploy:
  provider: pypi
  user: __token__
  password:
    secure: fcdPBMEMDrH+OjNiW5NQgnIEh4txSJi8r/g2mSwBFbnbINvABQDatPbMLkEEPEl44Jtt0ETd+IGyaivH8nVmP8JCQ1CBQQoIVEqDONWgyDAx/pbO+SyAo+cR/jfXMXWZKyK/2ZbDgPCxYm49LuQ92ff5r6giGjVPFf3Yf0zAp/a+0k/loLAgFCW81HLCvSwCBWMD0pKm1E5bePhFiE0HlmlRmqN0yyr/FRQSKqI3C/MGv+RMFxJgF2EWQlR8axolgT8CPNMQqw0XlbGvs+rpEoDvca7U7TrnKtlfCXyZQuF7T+al98oQojlUU2wUud+T+Xv16HpiZK9nuMVY5jY16ih7Lmc9zHSmyKr/yEjWWkeGu1GUDrLw7yMHLKVdInxena7sVBe+yM/wPJ3CzuFW+W+o2YBcWsok/jpGluqJcMAq+kka5bW3Cc4KjbY8ijtd2DhlncAbv0fH/GXnEAP2k1Gl4S6p24pUxwznZZ02EYpFC3rLJ8AabQ3QHWBT+cSt9wv9yvvPcH4WHRcX5ySMRdnrxKhfrAzvS6xcx2q31HOs33DeYZTqunC2z9Ub9K/t7UlL1CgvesvTcIGSqkxLhuJgP9wKg2hPjvDKr2Rxm7dDcdNgSpR6na9dKsrnuTvLc6abUtSJLIusLsABAS+tlu6Jm5DiXCWZi92UI+WgT6Y=
  on:
    tags: true
    repo: zhanglab/psamm
  distributions: sdist bdist_wheel
  skip_existing: true
