# Site settings
title: PSAMM
subtitle: Curation and Analysis of Metabolic Models
description: >
  PSAMM is an open source software that is designed for the curation and
  analysis of metabolic models. It supports model version tracking, model
  annotation, data integration, data parsing and formatting, consistency
  checking, automatic gap filling, and model simulations.
baseurl: "/psamm"
url: "https://zhanglab.github.io"
github_username: zhanglab

# Build settings
markdown: kramdown
